### ISSUE TITLE
Support ssdb

### ISSUE THREAD

**Issue by munrad** [alisaifee/coredis#70] opened 2022-06-30 12:19 UTC
Hello.
When using the library with ssdb, I get an error
![image](https://user-images.githubusercontent.com/11248604/176675707-358f1e7e-dba5-414b-ae45-3f177cc8c27a.png)

**Comment by alisaifee** [comment] 2022-06-30 14:41
I hadn't heard of ssdb before, but I was able to reproduce the error locally.

Looks like ssdb returns a different shaped error for 'unknown command' which is why it didn't fall back to assuming redis<6. Keep in mind that coredis version 4.x (which is what's on master) will start defaulting to RESP3 (though you can still pick `protocol_version=2`). I can do a workaround in the 3.x branch (which still defaults to RESP).

Out of curiosity - is there a stable docker image for ssdb? The CI does run against keydb & dragonfly and I'd like to add it in if possible.

**Comment by alisaifee** [comment] 2022-06-30 15:08
This is addressed by badbfd735b72c3985177c2e3c1e45680897ba461  and will be available in version `3.11.2` (which is still building).

**Closed by alisaifee** 2022-06-30 15:08 UTC
