### ISSUE TITLE
Connection Error("Invalid Database") raised if the db and decode_responses=True parameters is specified 

### ISSUE THREAD

**Issue by pribit** [alisaifee/coredis#46] opened 2022-04-21 09:29 UTC
Connection Error("Invalid Database") raised if the db and decode_responses=True parameters is specified.

[connection.py](https://github.com/alisaifee/coredis/blob/master/coredis/connection.py#L196)

        if self.db:
            await self.send_command(b"SELECT", self.db)

            if await self.read_response() != b"OK":
                raise ConnectionError("Invalid Database")

But if we add the decode=False parameter or compare it with "OK", the connection will be successful.
await self.read_response() actually return 'OK'.

I initialize ConnectionPool with the parameters decode_responses=True, encoding='utf-8' and db=1. Then I get a connection using the get_connection method and try to connect. If I remove decode_responses, the connection will also be successful.

I'm using python 3.10.2 with coredis==3.4.1
redis_version:5.0.4

**Comment by alisaifee** [comment] 2022-04-21 23:17
Thanks for the report and apologies for the regression (looks like this was introduced in `3.2.0`.
I'll cut a patch release shortly to address this.

**Comment by alisaifee** [comment] 2022-04-22 02:18
Fixed in [3.4.2](https://coredis.readthedocs.io/en/latest/release_notes.html#v3-4-2)

**Closed by alisaifee** 2022-04-22 02:18 UTC

**Comment by pribit** [comment] 2022-04-22 04:45
Thanks for the quick response. Now everything works!
